import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../index.css";
import Header from "@/components/header";
import Providers from "@/components/providers";
import localFont from "next/font/local";

const nebula = localFont({
  src: "../lib/fonts/NebulaSans-Book.woff2",
  variable: "--sans",
  display: "swap",
  weight: "400",
});

const palaise = localFont({
  src: "../lib/fonts/STFWaicena-Sans.otf",
  variable: "--palaise",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${nebula.variable} ${palaise.variable} antialiased`}>
        <Providers>
          <main className="  flex items-center  px-4 py-2 w-full h-svh flex-col bg-background ">
            <Header />
            <div className="flex-1 flex items-center justify-center mx-auto">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
